apiVersion: apps/v1
kind: Deployment
metadata:
  name: incoming-service
  labels:
    app: incoming-service
spec:
  selector:
    matchLabels:
      app: incoming-service
  template:
    metadata:
      labels:
        app: incoming-service
    spec:
      containers:
      - name: incoming-service
        image: localhost:32000/incoming-service:latest
        env:
          - name: SPRING_DATA_MONGODB_HOST
            value: "mongodb"
          - name: KAFKA_BOOTSTRAP_ADDRESS
            value: "kafka:9092"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: incoming-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.122.241
  selector:
    app: incoming-service
  ports:
  - port: 80
    targetPort: 8080
