apiVersion: v1
kind: Pod
metadata:
  name: incoming-service-test
spec:
  containers:
    - name: incoming-service-test
      image: 127.0.0.1:32000/incoming-service-test:latest
      env:
        - name: SPRING_DATA_MONGODB_HOST
          value: "mongodb"
        - name: KAFKA_BOOTSTRAP_ADDRESS
          value: "kafka:9092"
