apiVersion: apps/v1
kind: Deployment
metadata:
  name: incoming-read-service
  labels:
    app: incoming-read-service
spec:
  selector:
    matchLabels:
      app: incoming-read-service
  template:
    metadata:
      labels:
        app: incoming-read-service
    spec:
      containers:
      - name: incoming-read-service
        image: 127.0.0.1:32000/incoming-read-service:latest
        env:
          - name: SPRING_DATA_MONGODB_HOST
            value: "mongodb"
          - name: KAFKA_BOOTSTRAP_ADDRESS
            value: "kafka"
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: mongodb-root-password
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: incoming-read-service
spec:
  type: LoadBalancer
  selector:
    app: incoming-read-service
  ports:
  - port: 80
    targetPort: 8080
