apiVersion: apps/v1
kind: Deployment
metadata:
  name: incoming-persist
  labels:
    app: incoming-persist
spec:
  selector:
    matchLabels:
      app: incoming-persist
  template:
    metadata:
      labels:
        app: incoming-persist
    spec:
      containers:
      - name: incoming-persist
        image: 127.0.0.1:32000/incoming-persist:1.0-SNAPSHOT
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        
