apiVersion: v1
kind: Pod
spec:
  containers:
    - name: crictl
      image: gprasath/crictl:ci
      command: ["tail", "-f", "/dev/null"]
      resources:
        requests:
          memory: "256Mi"
          cpu: "125m"
        limits:
          memory: "256Mi"
